# Translation of Odoo Server.
# This file contains the translation of the following modules:
#	* account_ponto
#
msgid ""
msgstr ""
"Project-Id-Version: Odoo Server 12.0+e\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2019-11-20 14:30+0000\n"
"PO-Revision-Date: 2019-11-20 14:30+0000\n"
"Last-Translator: <>\n"
"Language-Team: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: \n"
"Plural-Forms: \n"

#. module: account_ponto
#: code:addons/account_ponto/models/ponto.py:42
#, python-format
msgid "Access to ponto using token is being deprecated. Please follow migration process on https://docs.google.com/document/d/1apzAtCgZl5mfEz5-Z8iETqd6WXGbV0R2KuAvEL87rBI"
msgstr ""

#. module: account_ponto
#: code:addons/account_ponto/models/ponto.py:134
#, python-format
msgid "Account"
msgstr ""

#. module: account_ponto
#: code:addons/account_ponto/models/ponto.py:113
#, python-format
msgid "An error occurred during online synchronization"
msgstr ""

#. module: account_ponto
#: code:addons/account_ponto/models/ponto.py:240
#, python-format
msgid "Fetching transactions took too much time."
msgstr ""

#. module: account_ponto
#: model:ir.model,name:account_ponto.model_account_online_journal
msgid "Interface for Online Account Journal"
msgstr ""

#. module: account_ponto
#: code:addons/account_ponto/models/ponto.py:70
#, python-format
msgid "Invalid access keys"
msgstr ""

#. module: account_ponto
#: code:addons/account_ponto/models/ponto.py:102
#, python-format
msgid "Link your Ponto account"
msgstr ""

#. module: account_ponto
#: selection:account.online.provider,provider_type:0
msgid "Plaid"
msgstr ""

#. module: account_ponto
#: selection:account.online.provider,provider_type:0
#: code:addons/account_ponto/models/ponto.py:160
#, python-format
msgid "Ponto"
msgstr ""

#. module: account_ponto
#: model:ir.model.fields,field_description:account_ponto.field_account_online_journal__ponto_last_synchronization_identifier
msgid "Ponto Last Synchronization Identifier"
msgstr ""

#. module: account_ponto
#: model:ir.model.fields,field_description:account_ponto.field_account_online_provider__ponto_token
msgid "Ponto Token"
msgstr ""

#. module: account_ponto
#: model:ir.model.fields,field_description:account_ponto.field_account_online_provider__provider_type
msgid "Provider Type"
msgstr ""

#. module: account_ponto
#: model:ir.model,name:account_ponto.model_account_online_provider
msgid "Provider for online account synchronization"
msgstr ""

#. module: account_ponto
#: code:addons/account_ponto/models/ponto.py:78
#, python-format
msgid "Server not reachable, please try again later"
msgstr ""

#. module: account_ponto
#: model:ir.model.fields,help:account_ponto.field_account_online_provider__ponto_token
msgid "Technical field that contains the ponto token"
msgstr ""

#. module: account_ponto
#: code:addons/account_ponto/models/ponto.py:114
#, python-format
msgid "The following error happened during the synchronization: %s"
msgstr ""

#. module: account_ponto
#: code:addons/account_ponto/models/ponto.py:75
#, python-format
msgid "Timeout: the server did not reply within 60s"
msgstr ""

#. module: account_ponto
#: model_terms:ir.ui.view,arch_db:account_ponto.ponto_online_provider_account_form_view
msgid "Update Accounts"
msgstr ""

#. module: account_ponto
#: selection:account.online.provider,provider_type:0
msgid "Yodlee"
msgstr ""

#. module: account_ponto
#: model:ir.model.fields,help:account_ponto.field_account_online_journal__ponto_last_synchronization_identifier
msgid "id of ponto synchronization"
msgstr ""

